# use the setting below to set multiple docs directories.
docSections = ["docs"]

uniqueHomePage = true # change to false to add sidebar to homepage

blogDir = "blog" # can be posts, blog e.t.c

repo = "https://github.com/ayj-develops/server-master"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 8

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

# Site logo
[logo]
  lightMode = "images/compose.png"
  darkMode = "images/compose-light.png"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/ayj-develops/server-master/"

# optional
# attribution. Feel free to delete this
[author]
  name = "Made by the AYJ Develops Team with ❤️. Built with Compose, made by Weru 2022."
  url = "https://github.com/ayj-develops/"
