title: AYJ Club Platform API Docs
email: ayjwebmasters@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a comprehensive reference for the AYJ Club Platform API. 
  Includes code snippets and request/response formats for the 
  front-end app integration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM

apispecs:
  homepage_title: AYJ Club Platform API Docs
  footer: AYJ Club Platform Team, 2022
  content_license: "CC BY-NC-SA 4.0"
  links:
    github: ayj-develops
    api_server: ayj-develops/server-master

github_edit:
  gh_edit_repository: ayj-develops/api-specs
  gh_edit_branch: "main"

collections:
  pages:
    output: true
    permalink: /:name
  docs:
    output: true
    permalink: /:collection/:name
  club-endpoint:
    output: true
    permalink: /:collection/:name
  comment-endpoint:
    output: true
    permalink: /:collection/:name
  post-endpoint:
    output: true
    permalink: /:collection/:name
  user-endpoint:
    output: true
    permalink: /:collection/:name
  admin-endpoint:
    output: true
    permalink: /:collection/:name
  release-notes:
    output: true
    permalink: /:collection/:name

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
