#  menu items

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[[main]]
  name = "Blog"
  weight = 5
  url = "blog/"

[[main]]
  name = "Apply"
  weight = 5
  url = "apply/"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"
